config/routes.rb
Rails.application.routes.draw do
  resources :eentries do
    resources :weekview
  end

  get 'pages/index'

  get 'pages/about'

  root :to => 'pages#index'

  get 'weekview', :to => 'eentries#weekview'
  get 'weekgraph', :to => 'eentries#weekgraph'

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  get 'graph/stacked'


  %w[about contact cv].each do |page|
    get page, controller: 'pages', action: page
  end

end

app/models/eentry.rb
class Eentry

  include Mongoid::Document
  field :user_id, type: Integer
  field :amount, type: Float
  field :tags, type: Array
  field :details, type: String
  field :created, type: DateTime
  field :updated, type: DateTime

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/eentries_controller.rb
require 'date'

class EentriesController < ApplicationController
  before_action :set_eentry, only: [:show, :edit, :update, :destroy]

  # GET /eentries
  # GET /eentries.json
  def index
    @eentries = Eentry.all.order_by(:created.desc)
  end

  # GET /eentries/1
  # GET /eentries/1.json
  def show
  end

  # GET /eentries/new
  def new
    @eentry = Eentry.new
  end

  # GET /eentries/1/edit
  def edit
  end

  # GET /eentries/1/weekview
  def weekview
    @first_day = (DateTime.now - 1.month).beginning_of_month
    @week_tags = []
    for i in 0..7
      @week_tags << (@first_day+i).strftime('%Y-%m-%d')
    end
    @eentries = Eentry.in(tags: @week_tags).order_by(:created.asc)
  end

  # POST /eentries
  # POST /eentries.json
  def create
    @eentry = Eentry.create
    @eentry.user_id = params[:eentry][:user_id]
    @eentry.amount = params[:eentry][:amount]
    @eentry.tags = params[:eentry][:tags].split(',').reject(&:empty?)
    @eentry.details = params[:eentry][:details]
    @eentry.created = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    @eentry.updated = Time.now.strftime("%Y-%m-%d %H:%M:%S")

    respond_to do |format|
      if @eentry.save
        format.html { redirect_to @eentry, notice: 'The entry was successfully created' }
        format.json { render :show, status: :created, location: @eentry }
      else
        format.html { render :new }
        format.json { render json: @eentry.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /eentries/1
  # PATCH/PUT /eentries/1.json
  def update
    respond_to do |format|
     @eentry = Eentry.find(params[:id])
      @eentry.user_id = params[:eentry][:user_id]
      @eentry.amount = params[:eentry][:amount]
      @eentry.tags = params[:eentry][:tags].split(',').reject(&:empty?)
      @eentry.details = params[:eentry][:details]
      @eentry.updated = Time.now.strftime("%Y-%m-%d %H:%M:%S")
      if @eentry.save
        format.html { redirect_to @eentry, notice: 'The entry was successfully updated' }
        format.json { render :show, status: :ok, location: @eentry }
      else
        format.html { render :edit }
        format.json { render json: @eentry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eentries/1
  # DELETE /eentries/1.json
  def destroy
    @eentry.destroy
    respond_to do |format|
      format.html { redirect_to eentries_url, notice: 'The entry was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private
    def set_eentry
      @eentry = Eentry.find(params[:id])
    end

    def eentry_params
      params.require(:eentry).permit(:user_id, :amount, :tags, :details)
    end
end

app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def index
  end

  def data
  end

  def stacked

    @find_tags = ["household", "food", "drinks", "transport"]
    @current_day  = (DateTime.now - 1.month).beginning_of_month
    @output = "date,household,food,drinks,transport"

    for week_no in 0..4
      @week_tags = []
      for i in 0..7
        @week_tags << (@current_day + (week_no * 7) + i).strftime('%Y-%m-%d')
      end
      @eentries = Eentry.in(tags: @week_tags).order_by(:created.asc)

      @current_line = Hash.new
      @find_tags.each do |tag|
        @current_line[tag] = 0
      end

      @eentries.each do |entry|
        tags = entry.tags

        tags.each do |tag|
          if @find_tags.include? tag
            @current_line[tag] += entry.amount.to_f
          end
        end

      end

      @output += "\n" + (@current_day + (week_no * 7)).strftime('%Y-%m-%d') + "," + ('%.2f' % @current_line["household"]).to_s + "," + ('%.2f' % @current_line["food"]).to_s + "," + ('%.2f' % @current_line["drinks"]).to_s + "," + ('%.2f' % @current_line["transport"]).to_s
    end

    respond_to do |format|
      format.html { render :layout => false }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eentries_helper.rb
module EentriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/eentries/_form.html.erb
<%= form_for(@eentry) do |f| %>
  <% if @eentry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eentry.errors.count, "error") %> prohibited this eentry from being saved:</h2>

      <ul>
      <% @eentry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eentries/edit.html.erb
<h1>Editing Eentry</h1>

<%= render 'form' %>

<%= link_to 'Show', @eentry %> |
<%= link_to 'Back', eentries_path %>

app/views/eentries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Eentries</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Amount</th>
      <th>Tags</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eentries.each do |eentry| %>
      <tr>
        <td><%= eentry.user_id %></td>
        <td><%= eentry.amount %></td>
        <td><%= eentry.tags %></td>
        <td><%= eentry.details %></td>
        <td><%= link_to 'Show', eentry %></td>
        <td><%= link_to 'Edit', edit_eentry_path(eentry) %></td>
        <td><%= link_to 'Destroy', eentry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Eentry', new_eentry_path %>

app/views/eentries/new.html.erb
<h1>New Eentry</h1>

<%= render 'form' %>

<%= link_to 'Back', eentries_path %>

app/views/eentries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @eentry.user_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @eentry.amount %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @eentry.tags %>
</p>

<p>
  <strong>Details:</strong>
  <%= @eentry.details %>
</p>

<%= link_to 'Edit', edit_eentry_path(@eentry) %> |
<%= link_to 'Back', eentries_path %>
<script>window.location.replace('http://localhost:3000/eentries');</script>

app/views/eentries/weekgraph.html.erb
<style>
    svg {
        width: 960px;
        height: 500px;
        border: solid 1px #ccc;
        font: 10px sans-serif;
        shape-rendering: crispEdges;
    }

</style>


<script>
    var w = 960,
            h = 500,
            p = [20, 50, 30, 20],
            x = d3.scale.ordinal().rangeRoundBands([0, w - p[1] - p[3]]),
            y = d3.scale.linear().range([0, h - p[0] - p[2]]),
            z = d3.scale.ordinal().range(["lightpink", "darkgray", "lightblue", "yellow"]),
            parse = d3.time.format("%Y-%m-%d").parse,
            format = d3.time.format("%Y-%m-%d");

    var svg = d3.select("body").append("svg:svg")
            .attr("width", w)
            .attr("height", h)
            .append("svg:g")
            .attr("transform", "translate(" + p[3] + "," + (h - p[2]) + ")");

    d3.csv("/graph/stacked", function(crimea) {
        console.log(crimea)

        // Transpose the data into layers by cause.
        var causes = d3.layout.stack()(["household", "food", "transport", "drinks"].map(function(cause) {
            return crimea.map(function(d) {
                return {x: parse(d.date), y: +d[cause]};
            });
        }));

        // Compute the x-domain (by date) and y-domain (by top).
        x.domain(causes[0].map(function(d) { return d.x; }));
        y.domain([0, d3.max(causes[causes.length - 1], function(d) { return d.y0 + d.y; })]);

        // Add a group for each cause.
        var cause = svg.selectAll("g.cause")
                .data(causes)
                .enter().append("svg:g")
                .attr("class", "cause")
                .style("fill", function(d, i) { return z(i); })
                .style("stroke", function(d, i) { return d3.rgb(z(i)).darker(); });

        // Add a rect for each date.
        var rect = cause.selectAll("rect")
                .data(Object)
                .enter().append("svg:rect")
                .attr("x", function(d) { return x(d.x); })
                .attr("y", function(d) { return -y(d.y0) - y(d.y); })
                .attr("height", function(d) { return y(d.y); })
                .attr("width", x.rangeBand());

        // Add a label per date.
        var label = svg.selectAll("text")
                .data(x.domain())
                .enter().append("svg:text")
                .attr("x", function(d) { return x(d) + x.rangeBand() / 2; })
                .attr("y", 6)
                .attr("text-anchor", "middle")
                .attr("dy", ".71em")
                .text(format);

        // Add y-axis rules.
        var rule = svg.selectAll("g.rule")
                .data(y.ticks(7))
                .enter().append("svg:g")
                .attr("class", "rule")
                .attr("transform", function(d) { return "translate(0," + -y(d) + ")"; });

        rule.append("svg:line")
                .attr("x2", w - p[1] - p[3])
                .style("stroke", function(d) { return d ? "#fff" : "#000"; })
                .style("stroke-opacity", function(d) { return d ? .7 : null; });

        rule.append("svg:text")
                .attr("x", w - p[1] - p[3] + 6)
                .attr("dy", ".35em")
                .text(d3.format(",d"));
    });

</script>

app/views/eentries/weekview.html.erb
<p id="notice"><%= @first_day %></p>
<p id="notice"><%= @week_tags %></p>
<p id="notice"><%= notice %></p>

<h1>Weekview Eentries</h1>

<table>
  <thead>
  <tr>
    <th>User</th>
    <th>Amount</th>
    <th>Tags</th>
    <th>Details</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @eentries.each do |eentry| %>
      <tr>
        <td><%= eentry.user_id %></td>
        <td><%= eentry.amount %></td>
        <td><%= eentry.tags %></td>
        <td><%= eentry.details %></td>
        <td><%= link_to 'Show', eentry %></td>
        <td><%= link_to 'Edit', edit_eentry_path(eentry) %></td>
        <td><%= link_to 'Destroy', eentry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Eentry', new_eentry_path %>
y

app/views/graph/data.json.erb
{
    "name": "flare",
    "children": [
        {
            "name": "Food",
            "children": [
                {
                    "name": "lunch",
                    "size": 802
                },
                {
                    "name": "shopping",
                    "children": [
                        {
                            "name": "shop1",
                            "size": 5000
                        },
                        {
                            "name": "shop2",
                            "size": 1000
                        }
                    ]
                }
            ]
        }
    ]
}

app/views/graph/index.html.erb
<style>
    circle {
        fill: rgb(31, 119, 180);
        fill-opacity: .25;
        stroke: rgb(31, 119, 180);
        stroke-width: 1px;
    }

    .leaf circle {
        fill: #ff7f0e;
        fill-opacity: 1;
    }

    text {
        font: 10px sans-serif;
    }
</style>

<script>
    var diameter = 960,
            format = d3.format(",d");

    var pack = d3.layout.pack()
            .size([diameter - 4, diameter - 4])
            .value(function(d) { return d.size; });

    var svg = d3.select("body").append("svg")
            .attr("width", diameter)
            .attr("height", diameter)
            .append("g")
            .attr("transform", "translate(2,2)");

    d3.json("data.json", function(error, root) {
        var node = svg.datum(root).selectAll(".node")
                .data(pack.nodes)
                .enter().append("g")
                .attr("class", function(d) { return d.children ? "node" : "leaf node"; })
                .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });

        node.append("title")
                .text(function(d) { return d.name + (d.children ? "" : ": " + format(d.size)); });

        node.append("circle")
                .attr("r", function(d) { return d.r; });

        node.filter(function(d) { return !d.children; }).append("text")
                .attr("dy", ".3em")
                .style("text-anchor", "middle")
                .text(function(d) { return d.name.substring(0, d.r / 3); });
    });

    d3.select(self.frameElement).style("height", diameter + "px");

</script>

app/views/graph/stacked.html.erb
<%= @output %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expense</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>input {width: 400px; height: 24px; font-family: Verdana;font-size:13px; }</style>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
notice = <%= @notice %>

app/views/pages/index.html.erb
notice = <%= @notice %>